name: Win10 Release

on:
  push:
    branches:
      - win10
  workflow_dispatch:
    inputs:
      version: 
        description: '版本号（不含v）'
        required: true
        default: '0.0.0.1'

jobs:
  release:
    runs-on: windows-latest

    env:
      SigningCertificate: CleanReader.Bundle_TemporaryKey.pfx
      Solution_Path: .\CleanReader.Desktop.sln
      Desktop_Project_Directory: src\CleanReader.Bundle
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION: "0.0.0.1"

    steps:
    
    - name: Configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.2
      with:
        minimum-size: 32GB
        maximum-size: 32GB
        disk-root: "C:"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: release-drafter/release-drafter@v5
      name: Create release draft
      id: release-drafter

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Update manifest version
      run: |
        [xml]$manifest = get-content ".\$env:Desktop_Project_Directory\Package.appxmanifest"
        $manifest.Package.Identity.Version = $env:VERSION
        $manifest.save(".\$env:Desktop_Project_Directory\Package.appxmanifest")
        
    - name: Build x64
      run: msbuild $env:Solution_Path /p:Platform=x64 /p:AppxBundlePlatforms="x64" /p:AppxPackageDir=C:\Package\x64 /p:PackageCertificateKeyFile=$env:SigningCertificate /p:PackageCertificatePassword="123456" /restore
      env:
        BuildMode: SideloadOnly
        Configuration: Release
   
    - name: Create x64 archive
      run: 7z a C:\Package\x64\CleanReader.Bundle_Test.7z C:\Package\x64\CleanReader.Bundle_0.0.0.1_Test

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: C:\Package\x64\CleanReader.Bundle_Test.7z
    - uses: actions/upload-artifact@v3
      with:
      name: CleanReader.Bundle_Test
      path: C:\Package\x64\CleanReader.Bundle_Test.7z